### ISSUE TITLE
LDM^ tests: Different results on console (GBP)

### ISSUE THREAD

**Issue by alyosha-tas** [GhostRain0/AGBEEG-Aging-Cartridge#3]
I tried running the LDM^ tests on my GBP and I got a different result ( 0x96A52A instead of 0x96871E )

The value I get seems to be from ORing both operands with user mode regs, while the expected value seems to come from only ORing the first operand with a user reg and using the correct value for the other one.

What hardware did you test on? I seem to get consistent results between runs, but I only have the GBP to test on.

**Comment by zaydlang** [comment]
Hmm, I ran it on a 3DS with open_agb_firm. Just double checked, and it seems to pass on that.

I think @fleroviux had a theory that this test depends on what register is read via register bus A vs register bus B during a multiply. Maybe this is different between the ARM7TDMI on the 3DS vs the GBP?

**Comment by alyosha-tas** [comment]
Hmmm, ok I'll try to make some tests that isolate the behavior here and tries a lot of variations. I'll report back my findings.

Thanks for the reply.

**Comment by alyosha-tas** [comment]
I have started working on some tests for this:

https://github.com/alyosha-tas/gba-tests/blob/master/LDM/LDM_ALU.gba

This test examines mul and add after an LDM^. On GBP, both operands are OR'd with user mode regs.

I also tried MLA, and in this case only the register that is to be added to the multiply result is OR'd with user regs.

By the way, your second test is executing from user mode. Not sure if this is intentional, but the test attempts to MSR to FIRQ mode from user mode which is not allowed (unprivileged) so I'm guessing not. 

EDIT: Also in ALU ops using a shift defined by a register, only register used for shifting is OR'd.

**Comment by fleroviux** [comment]
> Hmm, I ran it on a 3DS with open_agb_firm. Just double checked, and it seems to pass on that.

3DS GBA hardware is known to behave differently from GBA and GBA SP in this edge case. I don't remember what the 3DS hardware does but for GBA and GBA SP at least reads OR and writes go to both register banks.

**Comment by zaydlang** [comment]
Sorry I forgot to respond.

> By the way, your second test is executing from user mode. Not sure if this is intentional, but the test attempts to MSR to FIRQ mode from user mode which is not allowed (unprivileged) so I'm guessing not.

Yeah, oops, good catch.

> EDIT: Also in ALU ops using a shift defined by a register, only register used for shifting is OR'd.

I wonder if this is related to the order in which registers are fetched? Truth be told this was originally going to be a MUCH more difficult test. I heard stories about how the multiplication algorithm on the ARM7TDMI reads its input registers more than once, and decided to use the LDM^ trick to see if I can figure out the details. I couldn't, but I ended up with a test that seemingly broke emulators, so I added the test to the repo anyway.

> 3DS GBA hardware is known to behave differently from GBA and GBA SP in this edge case.

Hmm maybe I should revoke this test then, since it really doesn't test anything special.

**Comment by alyosha-tas** [comment]
> I wonder if this is related to the order in which registers are fetched? Truth be told this was originally going to be a MUCH more difficult test. I heard stories about how the multiplication algorithm on the ARM7TDMI reads its input registers more than once, and decided to use the LDM^ trick to see if I can figure out the details. I couldn't, but I ended up with a test that seemingly broke emulators, so I added the test to the repo anyway.

Yes access order is important, same for MLA. So far though I haven't been able to reproduce a case of writing to both user and banked registers, even when moving immediate values, I have some tests here: https://github.com/alyosha-tas/gba-tests/blob/master/LDM/LDM_ALU_Store.gba

@fleroviux do you have a specific example where this happens?

> Hmm maybe I should revoke this test then, since it really doesn't test anything special.

It could still be helpful to know it's something to look out for if any games accidentally rely on it.

**Comment by zaydlang** [comment]
> It could still be helpful to know it's something to look out for if any games accidentally rely on it.

Maybe, though I'd also like to get the original test working too. I'll go modify the test values

**Comment by zaydlang** [comment]
Can someone test on commit `3ec52f6`? I only have access to a 3DS

**Comment by alyosha-tas** [comment]
> Can someone test on commit `3ec52f6`? I only have access to a 3DS

Yup I get a pass for that version of the LDM^ test on GBP.

**Comment by fleroviux** [comment]
> @fleroviux do you have a specific example where this happens?

@alyosha-tas My statement probably is incorrect then. I based it on my implementation, but now I've realized that it most likely was a pure guess based on another bus conflict (regarding DS VRAM) that I saw before.

**Comment by alyosha-tas** [comment]
> > @fleroviux do you have a specific example where this happens?
> 
> @alyosha-tas My statement probably is incorrect then. I based it on my implementation, but now I've realized that it most likely was a pure guess based on another bus conflict (regarding DS VRAM) that I saw before.

Ok then, thanks for the reply. I plan on expanding my tests to be as broad as possible, so I'll report details if anything new comes up.
